apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: httpd-frontend
  template:
    metadata:
      labels:
        name: httpd-frontend
    spec:
      containers:
        - name: httpd-frontend
          image: httpd-frontend
    